export interface Product{
    Id:number,
    CategoryName:string,
    UnitName:string,
    Name:string,
    Code:string,
    ProductBarcode:string,
    Description:string,
    BrandName:string,
    SizeName:string,
    ColorName:string,
    ModelName:null,
    VariantName:null,
    OldPrice:number,
    Price:number,
    CostPrice:number,
    WarehouseList:never[],
    stock:number,
    TotalPurchase:number,
    LastPurchaseDate:string,
    LastPurchaseSupplier:string,
    TotalSales:number,
    LastSalesDate:string,
    LastSalesCustomer:string,
    ImagePath:null,
    Type:string,
    Status:string,


}