import { Component, OnInit } from '@angular/core';
import { Product } from 'src/app/models/product.model';
import { ProductsService } from 'src/app/services/products.service';

@Component({
  selector: 'app-products-list',
  templateUrl: './products-list.component.html',
  styleUrls: ['./products-list.component.css']
})
export class ProductsListComponent implements OnInit {

  products: Product[] = [];
//   [
//   {Id:45700,CategoryName:"Gadgets",UnitName:"Pcs",Name:"Airpods Pro  ANC",Code:"190199246997",ProductBarcode:"190199246997",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:0.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:0.0,LastPurchaseDate:"",LastPurchaseSupplier:"He",TotalSales:0.0,LastSalesDate: "",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45699,CategoryName:"Gadgets",UnitName:"Pcs",Name:"Airpods Pro  Fast Copy",Code:"321",ProductBarcode:"321",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:0.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"23-Aug-22",LastPurchaseSupplier:"He",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45698,CategoryName:"Mobile",UnitName:"Pcs",Name:"Narzo 30 - 6/128GB",Code:"6941399039216",ProductBarcode:"6941399039216",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:18500.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:2.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"Friends Communication",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45697,CategoryName:"Gadgets",UnitName:"Pcs",Name:"BASEUS WM01",Code:"123456",ProductBarcode:"123456",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:0.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"23-Aug-22",LastPurchaseSupplier:"He",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45696,CategoryName:"Gadgets",UnitName:"Pcs",Name:"BASEUS WM01 PLUS",Code:"1234",ProductBarcode:"1234",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:0.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"23-Aug-22",LastPurchaseSupplier:"Cash Supplier",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45695,CategoryName:"Gadgets",UnitName:"Pcs",Name:"COLOR SMART WATCH",Code:"3217",ProductBarcode:"3217",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:0.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:5.0,LastPurchaseDate:"23-Aug-22",LastPurchaseSupplier:"He",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45694,CategoryName:"Gadgets",UnitName:"Pcs",Name:"AIR BUDS ",Code:"4TH GREAD",ProductBarcode:"4TH GREAD",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:0.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:40.0,LastPurchaseDate:"23-Aug-22",LastPurchaseSupplier:"Cash Supplier",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45693,CategoryName:"Gadgets",UnitName:"Pcs",Name:"ONEPLUS BULLETS WIRELESS Z2",Code:"6921815620419",ProductBarcode:"6921815620419",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:0.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:0.0,LastPurchaseDate:"",LastPurchaseSupplier:"he",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45692,CategoryName:" IOT Products",UnitName:"Pcs",Name:"Apple-20w adepter",Code:"Apple-20w USB-C-Adapter",ProductBarcode:"Apple-20w USB-C-Adapter",Description:"",BrandName:"Anova",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:0.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"20-Aug-22",LastPurchaseSupplier:"FOREFRONT Electronic LTD",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45691,CategoryName:"Gadgets",UnitName:"Pcs",Name:"MagSafe Charger",Code:"194252192467",ProductBarcode:"194252192467",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:0.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:2.0,LastPurchaseDate:"23-Aug-22",LastPurchaseSupplier:"He",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45690,CategoryName:"Used Mobile",UnitName:"Pcs",Name:"Pixel 3XL - 4/128GB (Used)",Code:"53356563221",ProductBarcode:"53356563221",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:20000.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:2.0,LastPurchaseDate:"05-Aug-22",LastPurchaseSupplier:"Samrat Mobile",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45689,CategoryName:"Used Mobile",UnitName:"Pcs",Name:"Google Pixel 4XL - 6/64GB (Used)",Code:"325663255552",ProductBarcode:"325663255552",Description:"",BrandName:"",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:25000.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:2.0,LastPurchaseDate:"05-Aug-22",LastPurchaseSupplier:"Samrat Mobile",TotalSales:1.0,LastSalesDate:"22-Aug-22",LastSalesCustomer:"Walk In Customer",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45688,CategoryName:"CHOCOLATE",UnitName:"Pcs",Name:"PARK",Code:"22DBE2486",ProductBarcode:"22DBE2486",Description:"",BrandName:"N/A","SizeName":"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:15.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:30.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"DADA BHAI ENTERPRISE",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45687,CategoryName:"CHOCOLATE",UnitName:"Pcs",Name:"MILK BAR",Code:"22DBE2485",ProductBarcode:"22DBE2485",Description:"",BrandName:"N/A","SizeName":"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:15.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:24.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"DADA BHAI ENTERPRISE",TotalSales:1.0,LastSalesDate:"23-Aug-22",LastSalesCustomer:"Walk In Customer",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45686,CategoryName:"CHOCOLATE",UnitName:"Pcs",Name:"AMUL CHOCOLATE-SMALL",Code:"22DBE2487",ProductBarcode:"22DBE2487",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:60.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:20.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"DADA BHAI ENTERPRISE",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45685,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 68025",Code:"22SLI2461",ProductBarcode:"22SLI2461",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:1050.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45684,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 63780",Code:"22SLI2457",ProductBarcode:"22SLI2457",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:861.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45683,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 563712",Code:"22SLI2460",ProductBarcode:"22SLI2460",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:756.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45682,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 515246",Code:"22SLI2458",ProductBarcode:"22SLI2458",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:777.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45681,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 502382",Code:"22SLI2462",ProductBarcode:"22SLI2462",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:987.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45680,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 20840",Code:"22SLI2454",ProductBarcode:"22SLI2454",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:1428.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45679,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 164077",Code:"22SLI2455",ProductBarcode:"22SLI2455",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:1029.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45678,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 14614",Code:"22SLI2459",ProductBarcode:"22SLI2459",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:997.50,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45677,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 107101",Code:"22SLI2456",ProductBarcode:"22SLI2456",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:686.70,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45676,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 102343",Code:"22SLI2453",ProductBarcode:"22SLI2453",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:1386.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45675,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 102341",Code:"22SLI2451",ProductBarcode:"22SLI2451",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:1407.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45674,CategoryName:"Gift Items",UnitName:"Pcs",Name:"LADIS WALLET 07318",Code:"22SLI2452",ProductBarcode:"22SLI2452",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:1029.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:2.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45673,CategoryName:"Gift Items",UnitName:"Pcs",Name:"GENTS WALLET 505198",Code:"22SLI2464",ProductBarcode:"22SLI2464",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:1047.90,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45672,CategoryName:"Gift Items",UnitName:"Pcs",Name:"GENTS WALLET 502382",Code:"22SLI2469",ProductBarcode:"22SLI2469",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:987.00,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"},
//   {Id:45671,CategoryName:"Gift Items",UnitName:"Pcs",Name:"GENTS WALLET 20858",Code:"22SLI2468",ProductBarcode:"22SLI2468",Description:"",BrandName:"N/A",SizeName:"",ColorName:"",ModelName:null,VariantName:null,OldPrice:0.00,Price:764.40,CostPrice:0.0,WarehouseList:[],stock:0.0,TotalPurchase:1.0,LastPurchaseDate:"22-Aug-22",LastPurchaseSupplier:"SHREE LETHER INDIA-BABU DUTTA",TotalSales:0.0,LastSalesDate:"",LastSalesCustomer:" - ",ImagePath:null,Type:"simple",Status:"publish"}
// ]
  constructor(private productsService: ProductsService) { } //importing

  ngOnInit(): void {
    this.productsService.getAllProducts()
    .subscribe({
      next: (products) =>{
        this.products =products;
      },
      error: (response)=>{
        console.log(response);
      }
      
    })
  }

}
